## TFlearn を使った単層(中間層1層）ニューラルネットワークによる mnist の学習と評価

In [23]:
import tensorflow as tf
import tflearn

import tflearn.datasets.mnist as mnist

from matplotlib import pyplot as plt
from matplotlib import cm
import numpy as np

trainX, trainY, testX, testY = mnist.load_data('/tmp/data', one_hot=True) # tensorflow用　mnist の zip ファイルが有れば展開,無ければDL


tf.reset_default_graph()

net = tflearn.input_data(shape=[None, 784])

net = tflearn.fully_connected(net, 128, activation='relu') #ドロップアウト net = tflearn.dropout(net, 0.5) 無し
net = tflearn.fully_connected(net, 10, activation='softmax')
net = tflearn.regression(net, optimizer='sgd', learning_rate=0.5, loss='categorical_crossentropy')

model = tflearn.DNN(net)
model.fit(trainX, trainY, n_epoch=10, batch_size=100, validation_set=0.1, show_metric=True) # show_metricは,accuracy を毎回示すか否か

print('学習終了（上記の出力は，fit メソッドがかってに出力しています ⇒ ちょっと表示の詳細がわかりません．）')

Training Step: 4949  | total loss: 0.01555 | time: 5.141s
| SGD | epoch: 010 | loss: 0.01555 - acc: 0.9973 -- iter: 49400/49500
Training Step: 4950  | total loss: 0.01494 | time: 6.173s
| SGD | epoch: 010 | loss: 0.01494 - acc: 0.9976 | val_loss: 0.07450 - val_acc: 0.9796 -- iter: 49500/49500
--
学習終了（上記の出力は，fit メソッドがかってに出力しています ⇒ ちょっと表示の詳細がわかりません）


## 学習後の出力（sotfmax の値）と　正解の比較

In [24]:
print('1番目のデータの学習結果（softmaxの出力）')
soft_max=model.predict(testX)
print(soft_max[0])

print('1番目のデータの正解')
label_No1=testY
print(label_No1[0])

1番目のデータの学習結果（softmaxの出力）
[1.5359918e-08 3.8843442e-07 1.8704727e-06 9.1617167e-06 3.0096298e-10
 2.6328305e-08 2.6477013e-12 9.9998498e-01 5.4484730e-08 3.5832661e-06]
1番目のデータの正解
[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]


## 学習結果の評価

In [25]:
print('テストデータの適用')

x=model.predict(testX)
pred=np.array(x).argmax(axis=1) #.argmax は，行方向の何番目が最大値か表示  #pred= np.array(model.predict(testX).argmax(axis=1)) でも同じ
print(pred)

label= testY.argmax(axis=1) #.argmax は，行方向の何番目が最大値か表示
print(label)

accuracy=np.mean(pred == label, axis=0) #.argmax は，行方向の何番目が最大値か表示
print('正解率：', accuracy)

#  .argmax(axis=1)　の意味は以下のとおり．数値は，softmax の出力 ⇒ [7 2 ....]
#
#  No.1  No.2  ...
#  0.01  0.01  ...　⇒”０”
#  0.01  0.01  ...　⇒”１”
#  0.01  0.8   ...　⇒”２”
#  0.01  0.01  ...　⇒”３”
#  0.01  0.01  ...　⇒”４”
#  0.01  0.01  ...　⇒”５”
#  0.01  0.01  ...　⇒”６”
#  0.8   0.01  ...　⇒”７”
#  0.01  0.01  ...　⇒”８”
#  0.12  0.12  ...　⇒”９”


テストデータの適用
[7 2 1 ... 4 5 6]
[7 2 1 ... 4 5 6]
正解率： 0.9805


## 重み（パラメータ）の読み出し

In [26]:
w = model.get_weights(net.W)
print(w)

[[-0.00936289 -0.02111606  0.01085935 ... -0.02100659  0.05095698
  -0.05719079]
 [ 0.95485467 -0.7103018   0.46665657 ... -0.29727662  0.02813472
  -0.28480673]
 [-0.0792979  -0.18311383  0.00272807 ... -0.07392094  0.21661812
   0.01648906]
 ...
 [ 0.08264329  0.30492952  0.09187186 ...  0.6781584  -0.7667123
   0.45604545]
 [ 0.04947324  0.42203814  0.558784   ...  0.5374993  -0.44959804
   0.03372763]
 [-0.34026104  0.12387963 -0.46416128 ...  0.1937358   0.1043925
   0.47258824]]
