## 文字列と数値（型）

In [3]:
print('hello world')

hello world


In [6]:
print('1'+'99')

199


In [13]:
print(a)

NameError: name 'a' is not defined

In [7]:
print(1+99)

100


In [9]:
type('99')

str

In [10]:
type(99)

int

In [11]:
type(99.9)

float

## 変数

In [14]:
x='Yasunaga'
y='Moritoshi'
print(x)

Yasunaga


In [15]:
print(x+y)

YasunagaMoritoshi


In [1]:
a = 10
b = 1.23
print(a+b)

11.23


## 配列(リスト）

In [5]:
hairetsu = [[1,2,3],[4,5],[6]]

In [6]:
for x in hairetsu:
    print(x)
    

[1, 2, 3]
[4, 5]
[6]


## 繰り返し（for 文）

In [8]:
for atai in hairetsu:
    print(atai)
# 配列 hairetsu の 値 が 一回ごとに 変数 atai の中に入る．

[1, 2, 3]
[4, 5]
[6]


In [13]:
for row, atai in enumerate(hairetsu):
    print(row, atai)

# enumerata( ) によって，配列（リスト）の 行 に 行番号がつきます．
#  配列 hairetsu の 値 (行番号と値）が 一回ごとに 変数 row と　atai の中に入る．

0 [1, 2, 3]
1 [4, 5]
2 [6]


## 関数

In [26]:
def func(x,y):
    z = x*y
    return z

# 関数の範囲はインデントで表します．

num1 = 100
num2 = 3.14

z = func(num1, num2)
print(z)
print(type(z))

314.0
<class 'float'>


In [33]:
import numpy as np

hairetsu = [[1,2,3],[4,5,6],[7,8,9]]
array = np.array(hairetsu)
print ('array =', array)
print('hairetsu =', hairetsu)


array = [[1 2 3]
 [4 5 6]
 [7 8 9]]
hairetsu = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [37]:
print('各要素のデータ型：', array.dtype)
print('次元数：', array.size)
print(array/2)
print(array[0][0]/2)

各要素のデータ型： int32
次元数： 9
[[0.5 1.  1.5]
 [2.  2.5 3. ]
 [3.5 4.  4.5]]
0.5


In [42]:
flatten = array.flatten()
print('flatten_array =', flatten)

flatten_array = [1 2 3 4 5 6 7 8 9]


In [44]:
class GirlFriend(object):
    def change_name(self, name):
        self.name = name

girl_friend = GirlFriend()

# 1) メソッドでの呼び出し方
girl_friend.change_name('岩倉玲音') 
print(girl_friend.name)  # 岩倉玲音

# 2) 関数での呼び出し方
GirlFriend.change_name(girl_friend, 'サーバルちゃん')
print(girl_friend.name)  # サーバルちゃん

岩倉玲音
サーバルちゃん


In [46]:
from collections import Counter

hoge = ['a', 'b', 'c', 'a', 'a', 'c', 'b', 'd']

counter =Counter(hoge)
print(counter)

for elem, cnt in counter.most_common():
    print(elem, cnt)
    

Counter({'a': 3, 'c': 2, 'b': 2, 'd': 1})
a 3
c 2
b 2
d 1
